//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsRooms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsRoomsEntities : DbContext
    {
        public StudentsRoomsEntities()
            : base("name=StudentsRoomsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<District> Districts { get; set; }
        public DbSet<Owner_Table> Owner_Table { get; set; }
        public DbSet<Property_Table> Property_Table { get; set; }
        public DbSet<Review_Table> Review_Table { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Tehsile> Tehsiles { get; set; }
    }
}
