//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsRooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner_Table
    {
        public int owner_id { get; set; }
        public string owner_name { get; set; }
        public string owner_mobile1 { get; set; }
        public string owner_mobile2 { get; set; }
        public string owner_email { get; set; }
        public string owner_password { get; set; }
        public string status { get; set; }
        public string rts { get; set; }
    }
}
