//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsRooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehsile
    {
        public int TehsilId { get; set; }
        public string TehsilName { get; set; }
        public short DistrictId { get; set; }
    }
}
